### ISSUE TITLE
Quote versus corp-gray-bleed-bg voor Linkedin & Vcard in single-mensen

### ISSUE THREAD

**Issue by mrwebg** [mrwebg/corp_bootscore#10]
![Screenshot 2022-07-14 at 10-45-23 Diederik Baas - CORP  Advocaten](https://user-images.githubusercontent.com/93723380/178942274-909f0148-ee1a-412d-b3a2-a0479c9e26b7.png)

Sommige Team leden hebben een quote (van Chambers)
Als we die tonen komt het quote blok visueel in conflict met grey-bleed van Linkedin en Vcard.

Is het, om dit te vermijden niet beter om de Linkedin en vacard linkjes op te nemen, te tonen rechtstreeks in het wit onder de bestaande telefoon, mobiel en mail iconen?

**Comment by JonneBakker** [comment]
Ik heb 't aangepast, alle contact-buttons staan nu in één ul.

Vooralsnog heb ik het .corp-gray-bleed-bg element wel even laten staan in de template en een .d-none gegeven.
