### ISSUE TITLE
content featured post homepage niet als .lead tonen

### ISSUE THREAD

**Issue by JonneBakker** [mrwebg/corp_bootscore#2]
Tekst mag gewoon normale <p> zijn
<img width="559" alt="Screenshot 2022-06-22 at 14 37 34" src="https://user-images.githubusercontent.com/9334824/175030828-04ab4234-50e6-4c65-bb96-b81824744976.png">

**Comment by mrwebg** [comment]
He Jonne, bij het opzetten van de website heb ik voor de .lead class een generieke add_filter(the_content, etc aangezet.
Het lijkt me verstandig dat we deze lead class of de lead class properties in ieder geval oplossen met scss.
Ik kan namelijk niet in de add_filter(the_content targetten op een specifiek blokje content.

**Comment by mrwebg** [comment]
Misschien is het handig als ik daar waar we dat nodig hebben in de templates rondom <?php the_content();?> een <div wrapper zet met een class the-content zodat jij dan met scss kan targetten op .lead, .the-content p:first-of-type{  }

**Comment by JonneBakker** [comment]
Ik heb een css correctie toegevoegd. 
Extra wrapper is niet nodig, ik kan 'm op basis van template/element goed selecteren
