### ISSUE TITLE
single-mensen: content onderverdelen in into en overig

### ISSUE THREAD

**Issue by JonneBakker** [mrwebg/corp_bootscore#7]
I.v.m. layout (boven en onder dotted line) graag de content opknippen:
- 1 (huidige content?) wordt boven stippellijn geplaatst (align botton).
- 1: overige content (nieuw toe te voegen) wordt onder de stippellijn geplaatst 

Zie [design](https://xd.adobe.com/view/9cdf7ebe-fc0d-4b50-85c1-894dbd8e77ee-c98c/screen/f9f50541-4c01-455e-9676-5b36a172dc69) als voorbeeld.
In dit voorbeeld past de copy goed boven de stippellijn. Echter, bij veel content is het niet meer mogelijk deze mooi met de afbeelding uit te lijnen. 
Daarom dus graag een extra tekstveld tussen lijn en contact-icons waar eventueel extra tekst geplaatst kan worden.

Thanks!

**Comment by mrwebg** [comment]
Veld toegevoegd onder stippellijn row in bestaande col-lg-6
Als voorbeeld even Paul van den Belt genomen
Commit gedaan voor cmb2 fields en single-mensen.php
